Adicionando a regra que valida se o rich text tem um valor mínimo de caracteres
laboratoriobridge/validation pull request #52
Opened 2021-06-26 01:43 UTC by zDudaHang

closes #51

2021-06-28 13:24 UTC, lucasjoao requested changes
só uma dúvida e um detalhe, no mais ficou show de :soccer:

2021-06-28 13:24 UTC, lucasjoao commented on pom.xml
> +            </plugin>
Dúvida, foi necessário para o teste em kotlin poder ser executado na build?

2021-06-28 13:24 UTC, lucasjoao commented on src/main/kotlin/br/ufsc/bridge/platform/validation/rules/RichtTextMinLengthRule.kt
> +    private val htmlTagPattern = Regex("\\<.*?\\>|\n")
Detalhe, acho que vale colocar esse `Regex` em um `Util` (já existe um para o java...).

2021-06-28 13:50 UTC, Ishunter submitted a review, later dismissed

2021-06-28 14:30 UTC, continMarcelo approved these changes
Muito top Duda! :rocket:

2021-06-28 14:30 UTC, continMarcelo commented on src/main/kotlin/br/ufsc/bridge/platform/validation/rules/RichtTextMinLengthRule.kt
> +    private val htmlTagPattern = Regex("\\<.*?\\>|\n")
Era uma boa mesmo, colocar no mesmo estilo https://github.com/laboratoriobridge/validation/tree/master/src/main/java/br/ufsc/bridge/platform/validation/util mas pro Kotlin

2021-06-29 02:34 UTC, zDudaHang commented on pom.xml
> +            </plugin>
Sim, só rodava os testes de java

2021-06-29 02:34 UTC, zDudaHang commented on src/main/kotlin/br/ufsc/bridge/platform/validation/rules/RichtTextMinLengthRule.kt
> +    private val htmlTagPattern = Regex("\\<.*?\\>|\n")
Vou colocar !

2021-06-29 12:58 UTC, nathanmolinari approved these changes

2021-06-29 16:31 UTC, lucasjoao approved these changes

2021-06-29 16:37 UTC, continMarcelo approved these changes

2021-07-09 17:38 UTC, merged