Automatização do processo de release
laboratoriobridge/validation pull request #60
Opened 2021-09-03 14:17 UTC by zDudaHang

closes #58

2021-09-13 12:39 UTC, wagnerbsantos approved these changes

2021-09-13 12:48 UTC, lucasjoao requested changes
Comentei algumas dúvidas, no resto tá top!

2021-09-13 12:48 UTC, lucasjoao commented on .github/workflows/release.yml
> +          server-password: MAVEN_PASSWORD
Não deveria estar pegando do secrets? Ficou confuso para mim de onde essa informação vem.

2021-09-13 12:48 UTC, lucasjoao commented on .github/workflows/release.yml
> +          gpg-passphrase: MVN_RELEASE_GPG_PASSPHRASE
Ver comentário anterior.

2021-09-13 12:48 UTC, lucasjoao commented on pom.xml
> +                    <releaseProfiles>ossrh</releaseProfiles>
Porque esse id mais genérico ao invés de maven central?

2021-09-13 12:48 UTC, lucasjoao commented on .github/workflows/release.yml
> +          server-password: NEXUS_PASSWORD
Ver comentário sobre secrets

2021-09-13 12:48 UTC, lucasjoao commented on .github/workflows/release.yml
> +        run: mvn release:prepare -Possrh
Uma dúvida, a parte de remover o `SNAPSHOT` do `pom.xml` e incrementar é contemplada por aqui?

2021-09-13 12:48 UTC, lucasjoao commented on pom.xml
> +                    <url>${env.NEXUS_SNAPSHOT_URL}</url>
Aqui tais pegando o env do secrets, certo? Está certo usar o prefixo `env` ou deveria ser `secrets`?

2021-09-13 16:16 UTC, zDudaHang commented on .github/workflows/release.yml
> +          server-password: MAVEN_PASSWORD
Nessa parte do setup-java estou criando um _settings.xml_ que vai ter a tag `server` com as credenciais sendo: `env.MAVEN_USERNAME` e `env.MAVEN_PASSWORD`, cujos valores serão passados nas linhas 31 a 33.  [Um exemplo mostrando como ficaria o settings.xml](https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#publishing-using-apache-maven).

2021-09-13 16:17 UTC, zDudaHang commented on .github/workflows/release.yml
> +        run: mvn release:prepare -Possrh
Isso mesmo

2021-09-13 16:20 UTC, zDudaHang commented on pom.xml
> +                    <url>${env.NEXUS_SNAPSHOT_URL}</url>
Isso, eu passo os valores dos `secrets` para o `env`, daí o `pom` consegue definir esses valores certinho.
Não pesquisei se era possível colocar direto o `secrets` no pom, vou dar uma olhada

2021-09-13 16:37 UTC, zDudaHang commented on pom.xml
> +                    <releaseProfiles>ossrh</releaseProfiles>
Eu alterei o nome do perfil `release` para o `ossrh` (os plugins não foram alterados, só o nome mesmo), eu precisei alterar essa configuração do plugin para garantir que funcionaria certinho.

2021-09-14 16:49 UTC, lucasjoao commented on pom.xml
> +                    <url>${env.NEXUS_SNAPSHOT_URL}</url>
Por mim ok deixar assim, nem precisa olhar mais nada :upside_down_face:

2021-09-14 16:49 UTC, lucasjoao approved these changes
Bom d+ Duda!

2021-09-16 20:56 UTC, antoniotaha approved these changes

2021-09-17 15:20 UTC, merged