Ajuste na TelefoneRule e padronização da mensagem da RichTextMinLengthRule
laboratoriobridge/validation pull request #70
Opened 2022-07-25 14:22 UTC by gustavomoser

2022-07-25 17:20 UTC, biepes approved these changes

2022-07-25 20:53 UTC, lucasjoao requested changes
Boa Moser!

Uma possível melhoria ali só

2022-07-25 20:53 UTC, lucasjoao commented on src/main/java/br/ufsc/bridge/platform/validation/rules/TelefoneRule.java
> +
Fiquei em dúvida, mas não daria para resolver isso só alterando a ordem da verificação ali na linha 11?

Primeiro verificar se o regex bate para depois verificar se todos os números são iguais...

2022-07-26 17:06 UTC, gustavomoser commented on src/main/java/br/ufsc/bridge/platform/validation/rules/TelefoneRule.java
> +
Po, boa, realmente é uma melhor abordagem, vou fazer esse teste

2022-07-27 14:29 UTC, lucasjoao approved these changes
:rocket:

2022-08-01 13:59 UTC, MirianFS approved these changes
:top:

2022-08-01 14:33 UTC, antoniotaha approved these changes

2022-08-01 14:36 UTC, merged